---
version: "2.1"
services:
  docker-nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - /home/jq/home-env/gaming/win-server/sites-enabled:/etc/nginx/conf.d
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - WEBUI_PORT=5544
    volumes:
      - /mnt/g/MEGAsync/Media/Torrents/docker/qbittorrent:/config
      - /data:/data
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 5544:8080
    restart: unless-stopped
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /mnt/g/MEGAsync/Media/Torrents/docker/sonarr:/config
      - /data:/data
    ports:
      - 8989:8989
    restart: unless-stopped

# Based on https://trash-guides.info/Misc/how-to-set-up-hardlinks-and-atomic-moves/