---
version: "2.1"
services:
  docker-nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - /home/johqva/home-env/gaming/win-server/sites-enabled:/etc/nginx/conf.d
    restart: unless-stopped
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - WEBUI_PORT=5544
    volumes:
      - /mnt/g/MEGAsync/Media/Torrents/docker/qbittorrent:/config
      - /mnt/d/data:/data
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 5544:8080
    restart: unless-stopped
  sonarr:
    image: ghcr.io/linuxserver/sonarr:preview
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /mnt/g/MEGAsync/Media/Torrents/docker/sonarr:/config
      - /mnt/d/data:/data
    ports:
      - 8989:8989
    restart: unless-stopped
  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - AUTO_UPDATE=true
      #- RUN_OPTS=<run options here> #optional
    volumes:
      - /mnt/g/MEGAsync/Media/Torrents/docker/jackett:/config
    ports:
      - 9117:9117
    restart: unless-stopped
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /mnt/g/MEGAsync/Media/Torrents/docker/radarr:/config
      - /mnt/d/data:/data
    ports:
      - 7878:7878
    restart: unless-stopped
  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /mnt/g/MEGAsync/Media/Torrents/docker/sabnzbd:/config
      - /mnt/d/data:/data
    ports:
      - 8080:8080
      - 9090:9090
    restart: unless-stopped

  mylar3:
    image: ghcr.io/linuxserver/mylar3
    container_name: mylar3
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /mnt/g/MEGAsync/Media/Torrents/docker/mylar3:/config
      - /mnt/d/data:/data
    ports:
      - 8090:8090
    restart: unless-stopped
# Based on https://trash-guides.info/Misc/how-to-set-up-hardlinks-and-atomic-moves/