#!/usr/bin/env bash

echo 'Performing backup'

if test ! -d /mnt/e/Source; then
    echo Directory not found, something is wrong, exiting.
    exit
fi

echo "Copying Twitch videos"

mkdir -p '/mnt/e/Source/Videos/Twitch/Rewatchable'

rsync -av '/mnt/d/Source/Videos/Twitch/Rewatchable/' \
    '/mnt/e/Source/Videos/Twitch/Rewatchable'

echo "Copying Youtube videos"

mkdir -p '/mnt/e/Source/Videos/Youtube/Rewatchable'

rsync -av '/mnt/d/Source/Videos/Youtube/Rewatchable/' \
    '/mnt/e/Source/Videos/Youtube/Rewatchable'

rsync -av '/mnt/d/Source/Videos/Youtube/tartube.db' \
      '/mnt/e/Source/Videos/Youtube/tartube.db'

echo "Copying Media"

mkdir -p '/mnt/e/data/media'

rsync -av '/mnt/d/data/media/' '/mnt/e/data/media'

# echo "Removing all Kodi backups, except the last two."
# local_kodi_dir=//home/jq/.config/win-server/kodi
# everything_except_latest_backup=$(ls "$local_kodi_dir" | sort | head -n -2)
# for x in $everything_except_latest_backup; do
#     rm -rf "$local_kodi_dir/$x";
# done

rsync --delete -av '/home/jq/.config/win-server' \
    ~/myfiles/home/personal/torrents/

echo "Copying Terminal settings"

cp /mnt/c/Users/deffo/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json ~/home-env/terminal/settings.json
#      -v "$(wslpath "$(wslvar USERPROFILE)")/ProtonDrive/My files/home/personal/torrents/ai:/backup" \

docker run --rm \
      -v "ai_open-webui":/backup-volume \
      -v ~/myfiles/home/personal/ai:/backup \
      busybox \
      sh -c "cp -R /backup-volume/webui.db /backup/webui.db"

echo 'Done with backup'
sleep 3