#!/usr/bin/env bash

echo 'Performing backup'

if test ! -d /mnt/f/Source; then
    echo Directory not found, something is wrong, exiting.
    exit
fi

mkdir -p '/mnt/f/Source/Videos/Twitch/Rewatchable'

rsync -av '/mnt/d/Source/Videos/Twitch/Rewatchable/' \
    '/mnt/f/Source/Videos/Twitch/Rewatchable'

mkdir -p '/mnt/f/Source/Videos/Youtube/Rewatchable'

rsync -av '/mnt/d/Source/Videos/Youtube/Rewatchable/' \
    '/mnt/f/Source/Videos/Youtube/Rewatchable'

rsync -av '/mnt/d/Source/Videos/Youtube/tartube.db' \
      '/mnt/f/Source/Videos/Youtube/tartube.db'

mkdir -p '/mnt/f/data/media'

rsync -av '/mnt/d/data/media' '/mnt/f/data/media'

echo "Removing all Kodi backups, except the last two."
local_kodi_dir=/mnt/g/win-server/kodi
everything_except_latest_backup=$(ls "$local_kodi_dir" | sort | head -n -2)
for x in $everything_except_latest_backup; do
    rm -rf "$local_kodi_dir/$x";
done

rsync --delete -av '/mnt/g/win-server' \
    '/mnt/g/ProtonDrive/My files/Public/Media/Torrents/'

echo 'Done with backup'
sleep 3