#!/usr/bin/env bash

echo "Performing backup"

mkdir -p '/mnt/f/Source/Videos/Twitch/Rewatchable'

rsync -av --delete-delay '/mnt/d/Source/Videos/Twitch/Rewatchable/' \
    '/mnt/f/Source/Videos/Twitch/Rewatchable'

mkdir -p '/mnt/f/Source/Videos/Youtube/Rewatchable'

rsync -av --delete-delay '/mnt/d/Source/Videos/Youtube/Rewatchable/' \
    '/mnt/f/Source/Videos/Youtube/Rewatchable'

rsync -av '/mnt/d/Source/Videos/Youtube/tartube.db' \
    '/mnt/f/Source/Videos/Youtube/tartube.db'

mkdir -p '/mnt/f/data'

rsync -av '/mnt/d/data' '/mnt/f/data'

echo "Done with backup"
sleep 3