---
version: "2.1"
services:
  docker-nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - /home/jq/home-env/win-server/sites-enabled:/etc/nginx/conf.d
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - WEBUI_PORT=5544
    volumes:
      - /mnt/g/win-server/qbittorrent:/config
      - /mnt/d/data:/data
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 5544:8080
  sonarr:
    image: lscr.io/linuxserver/sonarr:develop
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /mnt/g/win-server/sonarr:/config
      - /mnt/d/data:/data
    ports:
      - 8989:8989
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - AUTO_UPDATE=true
    volumes:
      - /mnt/g/win-server/jackett:/config
    ports:
      - 9117:9117
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /mnt/g/win-server/radarr:/config
      - /mnt/d/data:/data
    ports:
      - 7878:7878
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /mnt/g/win-server/sabnzbd:/config
      - /mnt/d/data:/data
    ports:
      - 8080:8080
      - 9090:9090
# Based on https://trash-guides.info/Misc/how-to-set-up-hardlinks-and-atomic-moves/
