name: Local Assistant
version: 1.0.0
schema: v1
models:
  - name: google/gemma-3-27b-it:free
    provider: openrouter
    model: google/gemini-2.5-pro
    apiBase: https://openrouter.ai/api/v1
    apiKey: <OPENROUTER_API_KEY>
    roles:
      - chat
      - edit
      - apply
  - name: mistralai/codestral-2501
    provider: openrouter
    model: mistralai/codestral-2501
    apiBase: https://openrouter.ai/api/v1
    apiKey: <OPENROUTER_API_KEY>
    roles:
      - autocomplete
  - name: google/gemini-embedding-001
    provider: gemini
    model: gemini-embedding-001
    apiKey: <GOOGLE_GEMINI_API_KEY>
    roles:
      - embed
context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase
