name: Build

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Compile and Upload
        id: compile_and_upload
        uses: rust-build/rust-build.action@v1.4.4
        with:
          RUSTTARGET: x86_64-pc-windows-gnu
          UPLOAD_MODE: release