name: Build

on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: moonrepo/setup-rust@v1
        with:
          targets: 'x86_64-pc-windows-gnu'
      - name: Build
        run: cargo build --target x86_64-pc-windows-gnu 
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Development Build"
          files: |
            target/x86_64-pc-windows-gnu/debug/bootstrap.exe